spring:
  datasource:
    url: jdbc:mysql://localhost:3306/simple_blog
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: LeeJerry
    password: LeeJerry

  jpa:
    database: mysql
    properties:
      hibernate:
        show_sql : true

jwt:
  secret: ${SECRET_KEY}

url:
  server: ${SERVER_URL}
